### ISSUE TITLE
Header/Navbar

### ISSUE THREAD

**Issue by DevrajDC** [Design-and-Code/Linkify#18]

**Comment by DevrajDC** [comment]
![Frame 6](https://user-images.githubusercontent.com/65373279/123662775-66972a00-d853-11eb-8ca6-aea7330be70f.png)

**Comment by Mahich123** [comment]
I will do the task, pratham told to assigned it to me  .

**Comment by Prathamkrishna** [comment]
@DevrajDC :+1:

**Comment by DevrajDC** [comment]
Great, assigned it to @Mahich123

**Comment by ashusengar** [comment]
Just wanted to know if there's any scope of work left in the navbar

**Comment by DevrajDC** [comment]
> Just wanted to know if there's any scope of work left in the navbar

nothing as of now... will see if anything else is needed than I'll ping you! Also soon we will open new issues on this repo.
