### ISSUE TITLE
Hero Section

### ISSUE THREAD

**Issue by DevrajDC** [Design-and-Code/Linkify#19]

**Comment by DevrajDC** [comment]
![Frame 7](https://user-images.githubusercontent.com/65373279/123662889-7f074480-d853-11eb-8469-71ebf3b8a13c.png)

**Comment by lostgirljourney** [comment]
Falguni here! 👋🏼

**Comment by DevrajDC** [comment]
Great, assigned it to @lostgirljourney 
All the best!!

**Comment by Prathamkrishna** [comment]
hey @lostgirljourney. things to replace,
Lorem ipsum Loren ipsum: All your links in one place.
next line: The only link you'll ever need to connect with everyone in the world.

**Comment by lostgirljourney** [comment]
@Prathamkrishna and @DevrajDC understood. Everything cleared! :100:
