### ISSUE TITLE
Features section

### ISSUE THREAD

**Issue by DevrajDC** [Design-and-Code/Linkify#20]

**Comment by DevrajDC** [comment]
![Frame 8](https://user-images.githubusercontent.com/65373279/123662971-93e3d800-d853-11eb-9c7d-2a5d88fd0ca6.png)

**Comment by Barenyakumar** [comment]
i can work on it

**Comment by DevrajDC** [comment]
Okay great! @Prathamkrishna i am assigning this issue to @Barenyakumar

**Comment by DevrajDC** [comment]
Hey i am closing this issue. And we will be making new issue for features section again.
