### ISSUE TITLE
detailed description of feature section

### ISSUE THREAD

**Issue by DevrajDC** [Design-and-Code/Linkify#21]

**Comment by DevrajDC** [comment]
![Frame 9](https://user-images.githubusercontent.com/65373279/123663276-dd342780-d853-11eb-8c3c-958966518d24.png)

**Comment by OctoplusNinja** [comment]
Hey, I can work on this one.

**Comment by DevrajDC** [comment]
Okay Great, @Prathamkrishna i am assigning this issue to @OctoplusNinja

**Comment by DevrajDC** [comment]
Good job, closing this issue now.
