### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by DevrajDC** [Design-and-Code/Linkify#22]

**Comment by DevrajDC** [comment]
![Frame 10](https://user-images.githubusercontent.com/65373279/123663524-1b314b80-d854-11eb-9b4a-825d0c016d63.png)

**Comment by ANURAG0S1** [comment]
I could work on this

**Comment by DevrajDC** [comment]
Great!
@Prathamkrishna i am assigning @ANURAG0S1 this issue and you can have a talk with him later. Keep me updated.

**Comment by Prathamkrishna** [comment]
cool @DevrajDC,sounds good.

**Comment by Prathamkrishna** [comment]
hey @ANURAG0S1, any updates on the work done?

**Comment by nimishjn** [comment]
I can take up this issue

**Comment by Prathamkrishna** [comment]
@nimishjn sure, assigning it to you.

**Comment by nimishjn** [comment]
I finished the assigned task long time back. Is there anything to add yet?

**Comment by DevrajDC** [comment]
> I finished the assigned task long time back. Is there anything to add yet?

Add social icons instead of those circles in footer and hyperlink the community social handles to it. If you want the links than check: #about-us channel on discord.

**Comment by DevrajDC** [comment]
good job on the footer. I am closing this issue now.
