### ISSUE TITLE
Update Linkify ReadMe

### ISSUE THREAD

**Issue by DevrajDC** [Design-and-Code/Linkify#37]
- Add folder structure
- Add contribution guidlines
- Add banner
- add project maintainers and contributors

**Comment by nimishjn** [comment]
I'll take this up

**Comment by DevrajDC** [comment]
> I'll take this up

great! assigning it to you and adding you as the maintainer as well.
As a maintainer your responsibility is checking up on the PR created by the contributors and if its fine than merge it. You may also distribute and assign them work accordingly.

**Comment by nimishjn** [comment]
Got it. Thanks!

**Comment by DevrajDC** [comment]
Since its complete... i am closing this issue now!
