### ISSUE TITLE
Add darkmode toggle button in the navbar

### ISSUE THREAD

**Issue by DevrajDC** [Design-and-Code/Linkify#40]
Check the UI design to see how both themes look like.

**Comment by CSAURABH** [comment]
@DevrajDC  Can I work on this issue

**Comment by DevrajDC** [comment]
Yeah sure

**Comment by DevrajDC** [comment]
Join our Discord and ping me there. We can discuss it further!

**Comment by Rispectech** [comment]
hey can i work on this i already have a preview of u want

**Comment by Anubhavdevv** [comment]
Hey, @DevrajDC Can I contribute to this issue!

**Comment by DevrajDC** [comment]
> Hey, @DevrajDC Can I contribute to this issue!

Great assigned it to you!

**Comment by DevrajDC** [comment]
> hey can i work on this i already have a preview of u want

Maybe show it to me on discord. Join here: https://discord.gg/druweDMn3s
