### ISSUE TITLE
Footer update in mobile view

### ISSUE THREAD

**Issue by DevrajDC** [Design-and-Code/Linkify#41]
TODO:
- Remove Linkify name from footer.
- Center align the social icons.

Output Should be:
<img width="218" alt="Capture" src="https://user-images.githubusercontent.com/65373279/135468549-fd7cb8ee-92d8-4869-be56-375558a3ac5e.PNG">

**Comment by PuneetDabral** [comment]
sir can you please help me to do my contribution here i am new in git hub??!!

**Comment by PuneetDabral** [comment]
also assign it to me !!

**Comment by DevrajDC** [comment]
yeah sure!

**Comment by PuneetDabral** [comment]
what i can do sir ...can you please tell me step by step

**Comment by DevrajDC** [comment]
Okay. Are you on our discord? If yes than message me there and we can discuss it further!

**Comment by PuneetDabral** [comment]
yes i am can you please share the channel link

**Comment by DevrajDC** [comment]
Yes, i messaged you on discord! Lets discuss it further there :)

**Comment by maenad** [comment]
Hello! If this frees once again, please assign it to me! Have a great weekend!

**Comment by DevrajDC** [comment]
> Hello! If this frees once again, please assign it to me! Have a great weekend!

Sure, you may take it up since the other person has not started working on it. Also, join us on discord to discuss it further: https://discord.gg/druweDMn3s

**Comment by maenad** [comment]
> 
> 
> > Hello! If this frees once again, please assign it to me! Have a great weekend!
> 
> Sure, you may take it up since the other person has not started working on it. Also, join us on discord to discuss it further: https://discord.gg/druweDMn3s

Thanks a lot, will definitely do it ASAP.

**Comment by maenad** [comment]
Hello! I created a pull request for this issue. Please review it whenever you have some time. 

#55
