### ISSUE TITLE
[BUG] <Text overflow on iPad's horizontal view>

### ISSUE THREAD

**Issue by maenad** [Design-and-Code/Linkify#54]
### Description of the bug

I just did some quick check and this texts overflows when turning the iPad sideway.

Is it okay if I work on this issue for #hacktoberfest? If so, can you please add the tag to this issue?

Thanks in advance :)

### Working Environment (e.g. operating system, browser, device)

iPad

### Please add screenshots, if applicable (Drag & Drop your ss below)

![image](https://user-images.githubusercontent.com/31748140/135608412-b46c9dfe-522d-46fa-b4e7-80b65cd2b7e3.png)

**Comment by DevrajDC** [comment]
Sure, go ahead!

**Comment by maenad** [comment]
Hello! I created a pull request for this issue. Please review it whenever you have some time. 

#55

**Comment by DevrajDC** [comment]
Closing this issue, since you've already worked on it :)
