### ISSUE TITLE
[FEATURE] Add tech stack badges to README

### ISSUE THREAD

**Issue by Greeshma2903** [Design-and-Code/Linkify#57]
### Description of the feature, you want to add.

Adding badges of the tech stack used in the project will help contributors to sort through projects

### Mention if this feature is for any specific Working Environment (e.g. operating system, browser, device, N/A)

N/A

### Please add some pictorial references to the feature, if applicable (Drag & Drop your ss below)

Badges like these
![image](https://user-images.githubusercontent.com/70336930/135629643-38e21597-fe78-43c3-819b-5b6008a65de9.png)

### What will be your aprroach to add this feature?

I'll be adding the badges under the **Why this project?** part in the README
![image](https://user-images.githubusercontent.com/70336930/135629959-ec638d9d-4698-4fb8-a45b-9e852512871b.png)

**Comment by DevrajDC** [comment]
Yeah sounds good! Go on
