### ISSUE TITLE
[CONTENT] <I want to add some content in this site>

### ISSUE THREAD

**Issue by Mohasin-Haque** [Design-and-Code/Linkify#60]
### Description of the feature, you want to add.

I want to add some content for discord and welcome content so that to increase our community and help others to understand this site better.

### Mention if this feature is for any specific Working Environment (e.g. operating system, browser, device, N/A)

N/A

### What will be your aprroach to add this feature?

i will add the required contents.

**Comment by nimishjn** [comment]
@Mohasin-Haque 
Thank you for choosing the Design and Code repository. 
Please, share a sample design and also explain a bit more info. You may also join our discord server and ping one of the maintainers.

**Comment by nimishjn** [comment]
@Mohasin-Haque 
Are you working on this issue? If yes, then please acknowledge the previous comment.

**Comment by Mohasin-Haque** [comment]
I have not started working on it yet.. but will start soon.. thankyou for your patience.

**Comment by nimishjn** [comment]
Great @Mohasin-Haque. Assigning the issue to you. All the best!
