### ISSUE TITLE
[FEATURE] Login and Sign Up

### ISSUE THREAD

**Issue by nimishjn** [Design-and-Code/Linkify#62]
### Description of the feature, you want to add.

Add the Login and Sign Up modal on the homepage and trigger the modal on click of `Login` and `Sign Up` buttons.

### Mention if this feature is for any specific Working Environment (e.g. operating system, browser, device, N/A)

N/A

### Please add some pictorial references to the feature, if applicable (Drag & Drop your ss below)

![Login](https://user-images.githubusercontent.com/63140632/135657252-b6de331b-e93d-4bf0-b3cc-f090c93fc258.png)
![Sign Up](https://user-images.githubusercontent.com/63140632/135657346-76cdea34-c935-4f1f-b601-a859d84d3ea5.png)

### What will be your aprroach to add this feature?

- Create components for Login and Sign Up, so that they can be reused on other pages if required. 
- Keep a single modal with two tabs for Login and Sign Up respectively.

**Comment by Xaconi** [comment]
@nimishjn hey, can I grab this one?

**Comment by nimishjn** [comment]
@Xaconi Thank you for your interest in this repository.
Unfortunately, this issue has already been taken.

**Comment by Rispectech** [comment]
Submitted the pr  #65
