### ISSUE TITLE
[BUG] <iPad features are distended>

### ISSUE THREAD

**Issue by maenad** [Design-and-Code/Linkify#66]
### Description of the bug

Hello again!

I checked and somehow on the iPad/tablet and mobile views the features section looks like it has a ton of margin in between each one of them, this is probably related to the fixed height they have on the desktop view.

I would like to fix them, get them closer to each other and avoid the weird spaces between them.

EDIT: I also found the sign in/login popup in mobile to be too narrow, please see the screenshot below.

### Working Environment (e.g. operating system, browser, device)

iPad/Tablet and mobile (max-width: 1296px)

### Please add screenshots, if applicable (Drag & Drop your ss below)

![image](https://user-images.githubusercontent.com/31748140/136108628-123d4d1a-c89c-4172-a52b-6fbfecb681ee.png)
![image](https://user-images.githubusercontent.com/31748140/136109042-f8fb2dba-f21c-4431-b001-4c4d7f3a0242.png)

**Comment by nimishjn** [comment]
Hey @maenad, 
Thank you for registering this bug. 
Assigning issue #66 to you.

**Comment by DevrajDC** [comment]
Issue has been fixed so closing this one. Let's continue further discussion on our discord.
