### ISSUE TITLE
[FEATURE]: Tests to run on CI (GitHub Actions)

### ISSUE THREAD

**Issue by ShaileshKumar007** [Design-and-Code/Linkify#68]
### Description of the feature, you want to add.

Tests not running on push or pull request.

### Mention if this feature is for any specific Working Environment (e.g. operating system, browser, device, N/A)

NA

### Please add some pictorial references to the feature, if applicable (Drag & Drop your ss below)

NA

### What will be your aprroach to add this feature?

Added to GitHub Actions

### Any other context you have, to add here regarding this feature.

NA

**Comment by DevrajDC** [comment]
What do you exactly want to solve? The tests work fine only if a PR follows all the contribution guidelines.

**Comment by nimishjn** [comment]
> What do you exactly want to solve? The tests work fine only if a PR follows all the contribution guidelines.

@ShaileshKumar007 Please provide an answer to the question asked in the comment above.

**Comment by ShaileshKumar007** [comment]
I'm saying that no tests are running on push or pull requests. Therefore, I think it'll be good if we can add some tests in Github Actions so that these tests will check whether the PRs are valid or spammy.

**Comment by DevrajDC** [comment]
I don't have much idea on how GitHub actions will check the tests but You may go ahead and make a PR. I will see how it works, and if its of any benefit than will merge it 🚀

**Comment by ShaileshKumar007** [comment]
Ok. I'll soon generate a PR for that😃

**Comment by sidwebworks** [comment]
Let's first finish the features and create test cases before doing all this @DevrajDC
