### ISSUE TITLE
[FEATURE] UI Fix and Refactor components

### ISSUE THREAD

**Issue by nimishjn** [Design-and-Code/Linkify#70]
### Description of the feature, you want to add.

Minor tweaks of the Landing page components

### Mention if this feature is for any specific Working Environment (e.g. operating system, browser, device, N/A)

N/A

### Please add some pictorial references to the feature, if applicable (Drag & Drop your ss below)

- Hover effect
![image](https://user-images.githubusercontent.com/63140632/137592487-1c93157e-de6b-4f08-befb-590ff16dcaef.png)
- Background props in dark mode
![image](https://user-images.githubusercontent.com/63140632/137592514-71814427-ac4c-426a-93bb-9e8f179b819a.png)
- Feature section responsivity
![image](https://user-images.githubusercontent.com/63140632/137592537-a7721625-1aaf-4905-b874-892dd75baa61.png)

### What will be your aprroach to add this feature?

N/A

### Any other context you have, to add here regarding this feature.

No

**Comment by vaibhavch11** [comment]
can i work on this project.

**Comment by nimishjn** [comment]
Hey @vaibhavch11 
This issue has already been assigned for now. 
However, you are free to suggest changes and features by creating a new `issue`.
