### ISSUE TITLE
[FEATURE] Put social handles of Design and code in the center

### ISSUE THREAD

**Issue by ShaileshKumar007** [Design-and-Code/Linkify#71]
### Description of the feature, you want to add.

I think it looks good if we can shift the social icons present in the footer in the center which currently is present on the right side.

### Mention if this feature is for any specific Working Environment (e.g. operating system, browser, device, N/A)

NA

### Please add some pictorial references to the feature, if applicable (Drag & Drop your ss below)

![center](https://user-images.githubusercontent.com/71178959/137600045-c379a77c-7e07-4d1a-ae00-6043a8275b66.JPG)

### What will be your aprroach to add this feature?

Align these icons to the center.

### Any other context you have, to add here regarding this feature.

NA

**Comment by vaibhavch11** [comment]
can I work on this project.

**Comment by ShaileshKumar007** [comment]
Actually, only maintainers can assign the issues to someone. You can ask the maintainers about this by mentioning them in the comment.

**Comment by DevrajDC** [comment]
Hey folks, thanks for the suggestion. But the design has already been fixed so changing the layout of social icons would not matter as of now. We can discuss more issues on our discord channel and if it's a good one then I'll assign it to you'll.
Join here in case you haven't: https://discord.gg/druweDMn3s
