### ISSUE TITLE
[BUG] Deployment not found

### ISSUE THREAD

**Issue by sudip-mondal-2002** [Design-and-Code/Linkify#74]
### Description of the bug

The web page is not opening. It's showing 404 not found

### Working Environment (e.g. operating system, browser, device)

OS: Windows 11
Browser: Microsoft edge
Device: Dell Inspiron 3000 

### Please add screenshots, if applicable (Drag & Drop your ss below)

![image](https://user-images.githubusercontent.com/74463091/140779361-f870d504-b6af-4572-846c-03db95f9012c.png)

**Comment by nimishjn** [comment]
Hey @sudip-mondal-2002,
Check https://linkify-dc.netlify.app/ for the production deployment.
