### ISSUE TITLE
[BUG] Login click opens Sign up modal

### ISSUE THREAD

**Issue by JealousGx** [Design-and-Code/Linkify#75]
### Description of the bug

The title explains it all. When the user clicks on Login button, the sign up modal pops up instead of login modal.

### Working Environment (e.g. operating system, browser, device)

The bug occurs on Opera browser, Windows 10 OS.

### Please add screenshots, if applicable (Drag & Drop your ss below)

![image](https://user-images.githubusercontent.com/59867217/181876574-c06a0121-bdd0-4604-820a-438db1ebade2.png)
![image](https://user-images.githubusercontent.com/59867217/181876587-aac06458-28e7-493b-8610-73b79312c0e3.png)

**Comment by sidwebworks** [comment]
resolved, closing.
