### ISSUE TITLE
Just for fun

### ISSUE THREAD

**Issue by sidwebworks** [Design-and-Code/Linkify#77]
### Description of the bug

Sanju showed how to deploy the Shakalaka pencil on Vecel, BUT it does not seem to work.

Try cloning it locally and use the pencil at night in a dark room.

Need Reviews @DevrajDC @nimishjn @Shridhar-dev 

### Working Environment (e.g. operating system, browser, device)

- Vecel
- Bed room
- Drawing room

### Please add screenshots, if applicable (Drag & Drop your ss below)

![image](https://user-images.githubusercontent.com/58144379/183238573-dc41321d-805c-4c21-9190-d17cd1e89ceb.png)

![image](https://user-images.githubusercontent.com/58144379/183239002-bad3f9fd-86a8-432d-bb6f-c877a844aec8.png)

### Add any other context about the problem here

Need to resolve this ASAP to save Earth.

**Comment by Shridhar-dev** [comment]
@sidwebworks I went through the bug and tried to reproduce it on my system, seems like there is a significant bug in the foundation of the pencil. The Shakalaka boom boom pencil being a solid object needs to be first compiled down to a code format upon which we could inspect the internal of it and find the issue and resolve it.

**Comment by sidwebworks** [comment]
@Shridhar-dev Hmm interesting, seems like a bug in the core internals. I am afraid we are not specialized enough to deal with the problem at hand, I think the best resort to this problem would be to contact an external entity preferably from a different dimension.

@DevrajDC Try contacting Mars for help, if they don't respond see if the Neptune folks have any solutions.

**Comment by Shridhar-dev** [comment]
Upon inspecting the images, it came to my conclusion that you are using the 2001 model whereas the minimum package dependency requires it to be 2018 >=, since there isn't one available I think our last resort will be to ask @DevrajDC and take his opinion on this situation

**Comment by sidwebworks** [comment]
@Shridhar-dev Makes sense, we should get this done ASAP as its a matter of utmost urgency and looks like @DevrajDC is not taking this seriously.

**Comment by DevrajDC** [comment]
Okay will discuss this in today's meeting. Thanks for informing.
