### ISSUE TITLE
[BUG] Please change the favicon

### ISSUE THREAD

**Issue by aayushchugh** [Design-and-Code/Linkify#78]
### Description of the bug

Please change the favicon it's default react one now

### Working Environment (e.g. operating system, browser, device)

microsoft edge

### Please add screenshots, if applicable (Drag & Drop your ss below)

![image](https://user-images.githubusercontent.com/69336518/187037620-6a798b2e-a10b-41b0-bca8-2bcc3e7c9963.png)

**Comment by AHTHneeuhl** [comment]
Should I change It?

**Comment by AHTHneeuhl** [comment]
@aayushchugh  I fix this issue, can you close it!

**Comment by aayushchugh** [comment]
Ok
