### ISSUE TITLE
[BUG] Fix the PR template

### ISSUE THREAD

**Issue by Panquesito7** [Design-and-Code/Linkify#82]
### Description of the bug

The current pull request template seems to be following the wrong syntax that's used for issue templates. PR templates are made in Markdown and not YML. This should be fixed immediately.

This PR is one proof that the PR template is wrong https://github.com/Design-and-Code/Linkify/pull/81

### Working Environment (e.g. operating system, browser, device)

Browser.

**Comment by tharun634** [comment]
Hello, I'd like to work on this
